services:
  client:
    restart: always
    environment:
    - NODE_ENV=production
    ports:
    - 80:3000
  server:
    restart: always
    environment:
    - NODE_ENV=production
  mongodb:
    restart: always
