version: '3'
services:
    client:
        build: ./app/client
        container_name: "client"
        # restart: always
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        command:
            - ./app/client/run.sh
        volumes:
            - ./app/client:/app/client
            - /app/client/node_modules
        ports:
            - 3000:3000
        depends_on:
            - server
            - mongodb
    server:
        build: ./app/server
        container_name: "server"
        # restart: always
        environment:
            - NODE_ENV=development
        command:
            - ./app/server/run.sh
        volumes:
            - ./app/server:/app/server
            - /app/server/node_modules # Trick to get the container to see node_modules
        ports:
            - 4000:4000
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest # TODO not latest
        container_name: "mongodb"
        # restart: always
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod # --smallfiles --logpath=/dev/null # --quiet
