version: '3'
services:
  web:
    restart: always
    environment:
      - NODE_ENV=production
    command:
      - ./app/run.production.sh
    ports:
      - 80:4000
    #    volumes:
    #      - /etc/letsencrypt:/etc/letsencrypt
  mongodb:
    restart: always
