version: '3'
services:
    web:
        build: ./app
        container_name: "web"
        # restart: always
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - SERVER_PORT=4000
        command:
            - ./app/run.sh
        volumes:
            - ./app:/app
            - /app/server/node_modules # Trick to get the container to see node_modules
            - /app/client/node_modules
        ports:
            - 3000:3000
            - 4000:4000
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest # TODO not latest
        container_name: "mongodb"
        # restart: always
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod # --smallfiles --logpath=/dev/null # --quiet
